FROM python:3.9.5-slim-buster

ENV PYTHONBUFFERED=1
ENV FLASK_RUN_PORT=5000

RUN useradd -m -r -u 1000 newuser
USER newuser

WORKDIR /code

COPY requirements.txt /code/

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY /code  /code
